//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YChanEx {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class RegexStrings : global::System.Configuration.ApplicationSettingsBase {
        
        private static RegexStrings defaultInstance = ((RegexStrings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new RegexStrings())));
        
        public static RegexStrings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FourChanURL {
            get {
                return ((string)(this["FourChanURL"]));
            }
            set {
                this["FourChanURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FourTwentyChanURL {
            get {
                return ((string)(this["FourTwentyChanURL"]));
            }
            set {
                this["FourTwentyChanURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SevenChanURL {
            get {
                return ((string)(this["SevenChanURL"]));
            }
            set {
                this["SevenChanURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string EightChanURL {
            get {
                return ((string)(this["EightChanURL"]));
            }
            set {
                this["EightChanURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string fchanURL {
            get {
                return ((string)(this["fchanURL"]));
            }
            set {
                this["fchanURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string u18chanUrl {
            get {
                return ((string)(this["u18chanUrl"]));
            }
            set {
                this["u18chanUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string u18chanFiles {
            get {
                return ((string)(this["u18chanFiles"]));
            }
            set {
                this["u18chanFiles"] = value;
            }
        }
    }
}
